version: '3.8'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: devrootpass
      MYSQL_DATABASE: cookgen
      MYSQL_USER: cookgen
      MYSQL_PASSWORD: cookgen
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    build: ./
    container_name: CookGen
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: cookgen
      DATABASE_PASS: cookgen
      DATABASE_NAME: cookgen
      JWT_SECRET_KEY: Kx489P0XezHhihVk1lRUcuovtKo55P3OLawPqVyBSbc3
    ports:
      - '8000:8000'
    depends_on:
      - database

volumes:
  mysql-data: